services:
  docker-volume-backup:
    container_name: docker-volume-backup
    build:
      context: .
    command:
      - periodic-backups
      - --cron
      - "* * * * *"
      - --host-path
      - ${BACKUP_HOST_PATH}
      - --retention-days
      - "7"
      - --modes
      - "filesystem,s3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BACKUP_HOST_PATH}:/backups
    env_file:
      ./s3.env

  audiobookshelf:
    labels:
      ie.cianhatton.backup.enabled: "true"
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - AUDIOBOOKSHELF_UID=99
      - AUDIOBOOKSHELF_GID=100
    ports:
      - 13378:80
    volumes:
      - ${AUDIO_BOOKS_DIRECTORY}:/audiobooks
      - ${PODCASTS_DIRECTORY}:/podcasts
      - config:/config
      - metadata:/metadata
volumes:
  config:
  metadata:
