on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
      options: -v /__w/actions-test-repo/actions-test-repo:/zap/wrk/:rw
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - run: go test ./... -v
        env:
          CI: "true"
